trigger:
- master

# Must be linux in order for the environment variables to work
pool:
  vmImage: ubuntu-latest

steps:
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Archive only the build results
- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true

# The build results will be picked up by release pipeline (UI, no YAML)
- upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
  artifact: drop
