export const CONNECT_SERVER = 'CONNECT_SERVER';
export const DELETE_SERVER = 'DELETE_SERVER';
export const ADD_SERVER = 'ADD_SERVER';
export const CONNECT_SERVER_ERROR = 'CONNECT_SERVER_ERROR';
export const CONNECTING_SERVER = 'CONNECTING_SERVER';
export const SET_CURRENT_SERVER = 'SET_CURRENT_SERVER';

export const ADD_WEBSITE = 'ADD_WEBSITE';
